import type { Metadata } from "next";
import "./sass/globals.scss";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Test internetlab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body className='page'>
          <Header></Header>
          {children}
          <Footer></Footer>
        </body>
      </html>
  
  );
}
